# Generated by Django 5.2.1 on 2025-06-17 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cmspagecomponent',
            name='page',
        ),
        migrations.AlterField(
            model_name='accession',
            name='path',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='accession',
            name='component_id',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterModelOptions(
            name='groupurl',
            options={},
        ),
        migrations.AlterField(
            model_name='accession',
            name='permission',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='cms.expandedpermission'),
        ),
        migrations.DeleteModel(
            name='CMSPage',
        ),
        migrations.DeleteModel(
            name='CMSPageComponent',
        ),
    ]
