# Generated by Django 5.1.6 on 2025-04-12 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortcode_parameter',
            name='shortcode',
        ),
        migrations.DeleteModel(
            name='ShortCode',
        ),
        migrations.DeleteModel(
            name='ShortCode_Parameter',
        ),
    ]
