# Generated by Django 5.2.3 on 2025-06-13 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CMSPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(default='', max_length=255)),
                ('liminationtype', models.CharField(choices=[('withliminations', 'Страница с ограничениями'), ('withoutliminations', 'Страница без ограничений'), ('closepage', 'Закрытая страница')], default='withoutliminations', max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='groupurl',
            options={'default_permissions': ()},
        ),
        migrations.AlterField(
            model_name='accession',
            name='permission',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cms.expandedpermission'),
        ),
        migrations.AlterField(
            model_name='accession',
            name='path',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.cmspage'),
        ),
        migrations.CreateModel(
            name='CMSPageComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('componentid', models.CharField(default='', max_length=255)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.cmspage')),
            ],
        ),
        migrations.AlterField(
            model_name='accession',
            name='component_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.cmspagecomponent'),
        ),
    ]
