# Generated by Django 5.1.7 on 2025-04-02 08:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortcode',
            name='date_of_creation',
            field=models.DateField(default=datetime.datetime(2025, 4, 2, 11, 5, 20, 211958)),
        ),
        migrations.AlterField(
            model_name='shortcode',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 2, 11, 5, 20, 211958)),
        ),
    ]
