# Generated by Django 5.1.4 on 2025-03-11 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0002_delete_emailconfirmationcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Privelege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('function', models.CharField(choices=[('V', 'Visible'), ('X', 'Explotation')], default='V', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('Privelege', models.ManyToManyField(to='cms.privelege')),
            ],
        ),
    ]
