# Generated by Django 5.1.4 on 2025-03-12 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='Privelege',
        ),
        migrations.DeleteModel(
            name='Privelege',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
