# Generated by Django 5.1.4 on 2025-04-21 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_groupcategory_permissionmark_expandedgroup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expandedpermission',
            name='group_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cms.groupcategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expandedgroup',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.groupcategory'),
        ),
        migrations.AlterField(
            model_name='pageaccession',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.expandedpermission'),
        ),
    ]
