# Generated by Django 5.1.4 on 2025-04-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_expandedpermission_group_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecomponentaccession',
            name='component_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
