# Generated by Django 5.1.4 on 2025-04-23 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_alter_pagecomponentaccession_component_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageaccession',
            name='permission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cms.expandedpermission'),
        ),
        migrations.AlterField(
            model_name='pagecomponentaccession',
            name='permission',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='cms.expandedpermission'),
        ),
    ]
