# Generated by Django 5.1.4 on 2025-04-23 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_alter_pageaccession_permission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagecomponentaccession',
            name='permission',
        ),
        migrations.CreateModel(
            name='Accession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeaccession', models.CharField(default='PageAccession', max_length=100)),
                ('path', models.CharField(default='', max_length=255)),
                ('component_id', models.CharField(default='', max_length=255)),
                ('permission', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='cms.expandedpermission')),
            ],
        ),
        migrations.DeleteModel(
            name='PageAccession',
        ),
        migrations.DeleteModel(
            name='PageComponentAccession',
        ),
    ]
