# Generated by Django 5.1.4 on 2025-05-12 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_remove_pagecomponentaccession_permission_accession_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortcode_parameter',
            name='shortcode',
        ),
        migrations.DeleteModel(
            name='ShortCode',
        ),
        migrations.DeleteModel(
            name='ShortCode_Parameter',
        ),
    ]
