# Generated by Django 5.1.4 on 2025-05-12 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_remove_shortcode_parameter_shortcode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parentcategory',
        ),
        migrations.RemoveField(
            model_name='object',
            name='type',
        ),
        migrations.RemoveField(
            model_name='object',
            name='user',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Object_Type',
        ),
        migrations.DeleteModel(
            name='Object',
        ),
    ]
