# Generated by Django 5.1.4 on 2025-05-21 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_remove_category_parentcategory_remove_object_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accession',
            name='typeaccession',
        ),
    ]
