# Generated by Django 5.1.7 on 2025-05-27 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_cmspage_alter_accession_path_cmspagecomponent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accession',
            name='path',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.cmspage'),
        ),
        migrations.AlterField(
            model_name='accession',
            name='permission',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cms.expandedpermission'),
        ),
    ]
