# Generated by Django 5.1.7 on 2025-05-27 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_alter_accession_path_alter_accession_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accession',
            name='component_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.cmspagecomponent'),
        ),
    ]
