# Generated by Django 5.2.2 on 2025-06-11 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_default_creation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupurl',
            options={'default_permissions': ()},
        ),
    ]
