# Generated by Django 5.1.4 on 2024-12-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adpuser',
            old_name='surname',
            new_name='login',
        ),
        migrations.AddField(
            model_name='adpuser',
            name='password',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
