# Generated by Django 5.1.4 on 2024-12-20 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adp', '0003_alter_adpuser_email_alter_adpuser_login_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdpUser',
        ),
    ]
