# Generated by Django 5.2.4 on 2025-08-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies_parser_headhunter', '0003_remove_vacancyversion_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='salary_gross',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Зарплата до вычета налогов'),
        ),
    ]
