# Generated by Django 5.1.4 on 2024-12-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adp', '0002_rename_surname_adpuser_login_adpuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adpuser',
            name='email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='adpuser',
            name='login',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='adpuser',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='adpuser',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
