# Generated by Django 5.2.6 on 2025-10-01 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project_ed', '0022_remove_project_basic_provisions_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectBudgetTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_with_insurance', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Итого с страховкой')),
                ('salary_off_budget', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Зарплата (внебюджет)')),
                ('salary_budget', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Зарплата (бюджет)')),
                ('other_off_budget', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Другие расходы (внебюджет)')),
                ('other_budget', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Другие расходы (бюджет)')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_totals', to='project_ed.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Бюджет: итоги',
                'verbose_name_plural': 'Бюджет: итоги',
            },
        ),
        migrations.CreateModel(
            name='ProjectPlannedResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Планируемый результат')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_results', to='project_ed.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Планируемый результат',
                'verbose_name_plural': 'Планируемые результаты',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование этапа')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('planned_results', models.TextField(blank=True, default='', verbose_name='Планируемые результаты')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='project_ed.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Этап проекта',
                'verbose_name_plural': 'Этапы проекта',
                'ordering': ['order', 'start_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectBudgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_article', models.CharField(max_length=255, verbose_name='Статья расходов')),
                ('funding_source', models.CharField(max_length=255, verbose_name='Источник финансирования')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Сумма')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_items', to='project_ed.project', verbose_name='Проект')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_items', to='project_ed_projects.projectstage', verbose_name='Этап')),
            ],
            options={
                'verbose_name': 'Бюджет: позиция',
                'verbose_name_plural': 'Бюджет: позиции',
                'ordering': ['project_id', 'stage_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTargetIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('unit', models.CharField(blank=True, default='', max_length=50, verbose_name='Единица измерения')),
                ('baseline', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Базовое значение')),
                ('planned', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Планируемое значение')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_indicators_rel', to='project_ed.project', verbose_name='Проект')),
                ('source_indicator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_target_indicators', to='project_ed.targetindicator', verbose_name='Исходный целевой показатель')),
            ],
            options={
                'verbose_name': 'Целевой показатель проекта',
                'verbose_name_plural': 'Целевые показатели проекта',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Задача')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='project_ed.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Задача проекта',
                'verbose_name_plural': 'Задачи проекта',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectExecutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, default='', max_length=255, verbose_name='Роль в проекте')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executors', to='project_ed.project', verbose_name='Проект')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executed_projects', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Исполнитель проекта',
                'verbose_name_plural': 'Исполнители проекта',
                'unique_together': {('project', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ProjectVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(verbose_name='Номер версии')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='Заголовок/метка версии')),
                ('payload', models.JSONField(verbose_name='Снимок данных проекта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_ed_created_versions', to=settings.AUTH_USER_MODEL, verbose_name='Кем создано')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='project_ed.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Версия проекта',
                'verbose_name_plural': 'Версии проекта',
                'ordering': ['-created_at'],
                'unique_together': {('project', 'version_number')},
            },
        ),
    ]
