# Generated by Django 5.2.6 on 2025-10-02 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_ed', '0022_remove_project_basic_provisions_and_more'),
        ('project_ed_projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Роль в проекте')),
            ],
            options={
                'verbose_name': 'Роль проекта (справочник)',
                'verbose_name_plural': 'Роли проекта (справочник)',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectUserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='project_ed.project', verbose_name='Проект')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_links', to='project_ed_projects.projectrole', verbose_name='Роль')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_ed_roles', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Роль пользователя в проекте',
                'verbose_name_plural': 'Роли пользователей в проекте',
                'indexes': [models.Index(fields=['project', 'user'], name='project_ed__project_447b40_idx')],
                'unique_together': {('project', 'user', 'role')},
            },
        ),
    ]
