# Generated by Django 5.2.6 on 2025-10-06 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_ed', '0022_remove_project_basic_provisions_and_more'),
        ('project_ed_projects', '0003_populate_project_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Создание'), ('update', 'Обновление'), ('delete', 'Удаление'), ('status_change', 'Изменение статуса'), ('role_assign', 'Назначение роли'), ('role_remove', 'Удаление роли'), ('budget_change', 'Изменение бюджета'), ('stage_add', 'Добавление этапа'), ('stage_update', 'Обновление этапа'), ('stage_delete', 'Удаление этапа')], max_length=32, verbose_name='Действие')),
                ('model_type', models.CharField(choices=[('project', 'Проект'), ('project_task', 'Задача проекта'), ('project_executor', 'Исполнитель проекта'), ('project_planned_result', 'Планируемый результат'), ('project_target_indicator', 'Целевой показатель'), ('project_stage', 'Этап проекта'), ('project_budget_item', 'Бюджетная позиция'), ('project_budget_total', 'Бюджет итого'), ('project_user_role', 'Роль пользователя')], default='project', max_length=32, verbose_name='Тип модели')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID объекта')),
                ('field_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Название поля')),
                ('old_value', models.TextField(blank=True, default='', verbose_name='Старое значение')),
                ('new_value', models.TextField(blank=True, default='', verbose_name='Новое значение')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Метаданные')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='User-Agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время действия')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='project_ed.project', verbose_name='Проект')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_ed_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запись аудита проекта',
                'verbose_name_plural': 'Записи аудита проекта',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['project', 'timestamp'], name='project_ed__project_624a69_idx'), models.Index(fields=['user', 'timestamp'], name='project_ed__user_id_f35e12_idx'), models.Index(fields=['action', 'timestamp'], name='project_ed__action_71c871_idx'), models.Index(fields=['model_type', 'object_id'], name='project_ed__model_t_735871_idx')],
            },
        ),
    ]
