# Generated by Django 5.2.6 on 2025-10-11 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_ed', '0022_remove_project_basic_provisions_and_more'),
        ('project_ed_projects', '0004_projectauditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает проверки'), ('in_progress', 'В процессе проверки'), ('approved', 'Одобрен'), ('rejected', 'Отклонен'), ('needs_revision', 'Требует доработки')], default='pending', max_length=32, verbose_name='Статус проверки')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начата')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершена')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='project_ed.project', verbose_name='Проект')),
                ('version', models.ForeignKey(help_text='Версия проекта, которая проверяется', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='project_ed_projects.projectversion', verbose_name='Версия проекта')),
            ],
            options={
                'verbose_name': 'Экспертная проверка проекта',
                'verbose_name_plural': 'Экспертные проверки проектов',
                'ordering': ['started_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectReviewComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_data', models.JSONField(default=dict, help_text='JSON структура с данными замечания:\n        {\n            "section": "basic_provisions",           // Раздел проекта\n            "field": "projectName",                  // Поле проекта\n            "fieldDisplay": "Наименование проекта",  // Отображаемое название\n            "elementType": "field",                  // Тип элемента (field, task, stage, etc.)\n            "elementIndex": 0,                       // Индекс в массиве (если применимо)\n            "elementName": "Анализ требований",      // Название элемента\n            "elementPath": "projectTasks[0]",        // JSONPath к элементу\n            \n            "type": "warning",                       // Тип: critical, warning, suggestion, question, info\n            "priority": "medium",                    // Приоритет: low, medium, high, critical\n            "title": "Заголовок замечания",\n            "text": "Текст замечания",\n            \n            "oldValue": "Старое значение",           // Значение до исправления\n            "suggestedValue": "Предлагаемое значение", // Предлагаемое исправление\n            \n            "relatedObject": {                       // Связанный объект (если применимо)\n                "type": "project_task",\n                "id": 123\n            },\n            \n            "metadata": {                            // Дополнительные данные\n                "context": "Контекст замечания",\n                "references": ["ссылка1", "ссылка2"]\n            }\n        }', verbose_name='Данные замечания')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Исправлено')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Исправлено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_review_comments', to=settings.AUTH_USER_MODEL, verbose_name='Эксперт')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_project_comments', to=settings.AUTH_USER_MODEL, verbose_name='Исправил')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='project_ed_projects.projectreview', verbose_name='Проверка проекта')),
            ],
            options={
                'verbose_name': 'Замечание эксперта',
                'verbose_name_plural': 'Замечания экспертов',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['review', 'is_resolved'], name='project_ed__review__a17db1_idx'), models.Index(fields=['expert', 'created_at'], name='project_ed__expert__782f88_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProjectReviewDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('approve', 'Одобрить'), ('reject', 'Отклонить'), ('needs_revision', 'Требует доработки')], max_length=32, verbose_name='Решение')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий к решению')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_review_decisions', to=settings.AUTH_USER_MODEL, verbose_name='Эксперт')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='project_ed_projects.projectreview', verbose_name='Проверка проекта')),
            ],
            options={
                'verbose_name': 'Решение эксперта',
                'verbose_name_plural': 'Решения экспертов',
                'ordering': ['-created_at'],
                'unique_together': {('review', 'expert')},
            },
        ),
        migrations.CreateModel(
            name='ProjectReviewExpert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('assigned', 'Назначен'), ('started', 'Начал проверку'), ('completed', 'Завершил проверку')], default='assigned', max_length=32, verbose_name='Статус эксперта')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Назначен')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начал проверку')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершил проверку')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_review_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Эксперт')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_experts', to='project_ed_projects.projectreview', verbose_name='Проверка проекта')),
            ],
            options={
                'verbose_name': 'Эксперт проверки проекта',
                'verbose_name_plural': 'Эксперты проверки проекта',
                'ordering': ['assigned_at'],
                'unique_together': {('review', 'expert')},
            },
        ),
    ]
