# Generated by Django 5.2.6 on 2025-09-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porosity_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='porosityanalysis',
            name='duration_seconds',
            field=models.IntegerField(blank=True, null=True, verbose_name='Длительность (сек)'),
        ),
        migrations.AddField(
            model_name='porosityanalysis',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время завершения'),
        ),
        migrations.AddField(
            model_name='porosityanalysis',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время старта'),
        ),
    ]
