# Generated by Django 5.2.6 on 2025-09-30 09:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porosity_analysis', '0002_porosityanalysis_duration_seconds_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PorosityGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название группы')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Группа анализов пористости',
                'verbose_name_plural': 'Группы анализов пористости',
                'db_table': 'porosity_analysis_group',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='porosityanalysis',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses', to='porosity_analysis.porositygroup', verbose_name='Группа'),
        ),
    ]
