# Generated by Django 5.2.6 on 2025-10-06 17:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porosity_analysis', '0003_porositygroup_porosityanalysis_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='PorosityArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название архива')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('file_path', models.CharField(max_length=500, verbose_name='Путь к файлу архива')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='Размер файла (байты)')),
                ('report_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word')], default='docx', max_length=10, verbose_name='Тип отчета')),
                ('status', models.CharField(choices=[('creating', 'Создается'), ('completed', 'Создан'), ('failed', 'Ошибка')], default='creating', max_length=20, verbose_name='Статус')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('analyses', models.ManyToManyField(related_name='archives', to='porosity_analysis.porosityanalysis', verbose_name='Анализы в архиве')),
            ],
            options={
                'verbose_name': 'Архив отчетов пористости',
                'verbose_name_plural': 'Архивы отчетов пористости',
                'db_table': 'porosity_analysis_archive',
                'ordering': ['-created_at'],
            },
        ),
    ]
