# Generated by Django 5.2.6 on 2025-10-06 17:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porosity_analysis', '0004_porosityarchive'),
    ]

    operations = [
        migrations.AddField(
            model_name='porosityarchive',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID архива'),
        ),
    ]
