# Generated by Django 5.2.6 on 2025-10-06 18:41

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porosity_analysis', '0005_porosityarchive_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Токен')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('expires_at', models.DateTimeField(verbose_name='Дата истечения')),
                ('file_type', models.CharField(choices=[('archive', 'Архив'), ('report', 'Отчет'), ('original', 'Исходное изображение')], max_length=20, verbose_name='Тип файла')),
                ('object_id', models.IntegerField(verbose_name='ID объекта')),
                ('params', models.JSONField(blank=True, default=dict, verbose_name='Параметры')),
                ('is_used', models.BooleanField(default=False, verbose_name='Использован')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Время использования')),
            ],
            options={
                'verbose_name': 'Токен скачивания',
                'verbose_name_plural': 'Токены скачивания',
                'db_table': 'porosity_download_token',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token', 'expires_at'], name='porosity_do_token_2c7a95_idx')],
            },
        ),
    ]
