# Generated by Django 5.2.6 on 2025-09-18 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=255, verbose_name='Краткое наименование')),
                ('name', models.TextField(verbose_name='Наименование проекта')),
                ('name_clarification', models.CharField(blank=True, max_length=255, verbose_name='Уточняющее наименование')),
                ('start_date', models.DateField(verbose_name='Дата начала проекта')),
                ('end_date', models.DateField(verbose_name='Дата окончания проекта')),
                ('curator_id', models.IntegerField(blank=True, null=True, verbose_name='Куратор (ID)')),
                ('customer_name', models.CharField(blank=True, max_length=255, verbose_name='Заказчик')),
                ('manager_name', models.CharField(blank=True, max_length=255, verbose_name='Руководитель проекта')),
                ('budget_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Бюджет (с учетом взносов)')),
                ('event', models.JSONField(blank=True, null=True, verbose_name='Выбранное мероприятие')),
                ('basic_provisions', models.JSONField(default=dict, verbose_name='Основные положения')),
                ('target_indicators', models.JSONField(default=list, verbose_name='Целевые показатели')),
                ('calendar_plan', models.JSONField(default=dict, verbose_name='Календарный план')),
                ('budget', models.JSONField(default=dict, verbose_name='Бюджет')),
                ('additional_info', models.JSONField(default=dict, verbose_name='Дополнительная информация')),
                ('status', models.CharField(default='draft', max_length=32, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_ed_projects', to=settings.AUTH_USER_MODEL, verbose_name='Владелец проекта')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-created_at'],
            },
        ),
    ]
