# Generated by Django 5.2.6 on 2025-09-20 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, verbose_name='Описание категории')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Категория показателей',
                'verbose_name_plural': 'Категории показателей',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=255, verbose_name='Краткое наименование')),
                ('name', models.TextField(verbose_name='Наименование проекта')),
                ('name_clarification', models.CharField(blank=True, max_length=255, verbose_name='Уточняющее наименование')),
                ('start_date', models.DateField(verbose_name='Дата начала проекта')),
                ('end_date', models.DateField(verbose_name='Дата окончания проекта')),
                ('curator_id', models.IntegerField(blank=True, null=True, verbose_name='Куратор (ID)')),
                ('customer_name', models.CharField(blank=True, max_length=255, verbose_name='Заказчик')),
                ('manager_name', models.CharField(blank=True, max_length=255, verbose_name='Руководитель проекта')),
                ('budget_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Бюджет (с учетом взносов)')),
                ('event', models.JSONField(blank=True, null=True, verbose_name='Выбранное мероприятие')),
                ('basic_provisions', models.JSONField(default=dict, verbose_name='Основные положения')),
                ('target_indicators', models.JSONField(default=list, verbose_name='Целевые показатели')),
                ('calendar_plan', models.JSONField(default=dict, verbose_name='Календарный план')),
                ('budget', models.JSONField(default=dict, verbose_name='Бюджет')),
                ('additional_info', models.JSONField(default=dict, verbose_name='Дополнительная информация')),
                ('status', models.CharField(default='draft', max_length=32, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_ed_projects', to=settings.AUTH_USER_MODEL, verbose_name='Владелец проекта')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название подкатегории')),
                ('description', models.TextField(blank=True, verbose_name='Описание подкатегории')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='project_ed.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Подкатегория показателей',
                'verbose_name_plural': 'Подкатегории показателей',
                'ordering': ['order', 'name'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TargetIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название показателя')),
                ('description', models.TextField(blank=True, verbose_name='Описание показателя')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='Единица измерения')),
                ('target_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Целевое значение')),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Текущее значение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_indicators', to='project_ed.category', verbose_name='Категория')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_target_indicators', to='project_ed.project', verbose_name='Проект')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_indicators', to='project_ed.subcategory', verbose_name='Подкатегория')),
            ],
            options={
                'verbose_name': 'Целевой показатель',
                'verbose_name_plural': 'Целевые показатели',
                'ordering': ['category__order', 'subcategory__order', 'name'],
            },
        ),
    ]
