# Generated by Django 5.2.6 on 2025-09-20 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_ed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название блока')),
                ('description', models.TextField(blank=True, verbose_name='Описание блока')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_blocks', to='project_ed.category', verbose_name='Категория')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_blocks', to='project_ed.subcategory', verbose_name='Подкатегория')),
            ],
            options={
                'verbose_name': 'Блок мероприятий',
                'verbose_name_plural': 'Блоки мероприятий',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='Код мероприятия')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование мероприятия')),
                ('results', models.TextField(blank=True, verbose_name='Основные результаты')),
                ('start_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год начала')),
                ('end_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год окончания')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='project_ed.eventblock', verbose_name='Блок мероприятий')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
                'ordering': ['block__order', 'order', 'name'],
            },
        ),
    ]
