# Generated by Django 5.2.6 on 2025-09-20 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_ed', '0002_eventblock_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='targetindicator',
            name='event_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_indicators', to='project_ed.eventblock', verbose_name='Блок мероприятий'),
        ),
        migrations.AddField(
            model_name='targetindicator',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_indicators', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный'),
        ),
        migrations.AddField(
            model_name='targetindicator',
            name='values_by_year',
            field=models.JSONField(blank=True, default=dict, verbose_name='Значения по годам'),
        ),
    ]
