# Generated by Django 5.2.6 on 2025-09-20 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_ed', '0003_targetindicator_event_block_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventblock',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Код блока'),
        ),
    ]
