# Generated by Django 5.2.6 on 2025-09-22 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_ed', '0004_eventblock_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectEdUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=100, verbose_name='Роль в проекте')),
                ('position', models.CharField(blank=True, max_length=255, verbose_name='Должность')),
                ('faculty', models.CharField(blank=True, max_length=255, verbose_name='Факультет')),
                ('department', models.CharField(blank=True, max_length=255, verbose_name='Кафедра')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_ed_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя ProjectEd',
                'verbose_name_plural': 'Профили пользователей ProjectEd',
            },
        ),
    ]
