# Generated by Django 5.2.6 on 2025-09-22 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_ed', '0005_projecteduserprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectEdDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Кафедра ProjectEd',
                'verbose_name_plural': 'Кафедры ProjectEd',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectEdFaculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Факультет ProjectEd',
                'verbose_name_plural': 'Факультеты ProjectEd',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectEdPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Должность ProjectEd',
                'verbose_name_plural': 'Должности ProjectEd',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectEdRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Роль ProjectEd',
                'verbose_name_plural': 'Роли ProjectEd',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='projecteduserprofile',
            name='department',
            field=models.CharField(blank=True, max_length=255, verbose_name='Кафедра (строка)'),
        ),
        migrations.AlterField(
            model_name='projecteduserprofile',
            name='faculty',
            field=models.CharField(blank=True, max_length=255, verbose_name='Факультет (строка)'),
        ),
        migrations.AlterField(
            model_name='projecteduserprofile',
            name='position',
            field=models.CharField(blank=True, max_length=255, verbose_name='Должность (строка)'),
        ),
        migrations.AlterField(
            model_name='projecteduserprofile',
            name='role',
            field=models.CharField(blank=True, max_length=100, verbose_name='Роль в проекте (строка)'),
        ),
        migrations.AddField(
            model_name='projecteduserprofile',
            name='department_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='project_ed.projecteddepartment', verbose_name='Кафедра (справочник)'),
        ),
        migrations.AddField(
            model_name='projecteduserprofile',
            name='faculty_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='project_ed.projectedfaculty', verbose_name='Факультет (справочник)'),
        ),
        migrations.AddField(
            model_name='projecteduserprofile',
            name='position_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='project_ed.projectedposition', verbose_name='Должность (справочник)'),
        ),
        migrations.AddField(
            model_name='projecteduserprofile',
            name='role_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='project_ed.projectedrole', verbose_name='Роль (справочник)'),
        ),
    ]
