# Generated by Django 5.2.6 on 2025-09-22 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_ed', '0006_projecteddepartment_projectedfaculty_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectEdDepartment',
            new_name='Department',
        ),
        migrations.RenameModel(
            old_name='ProjectEdRole',
            new_name='Faculty',
        ),
        migrations.RenameModel(
            old_name='ProjectEdPosition',
            new_name='Position',
        ),
        migrations.RenameModel(
            old_name='ProjectEdFaculty',
            new_name='Role',
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'ordering': ['name'], 'verbose_name': 'Факультет ProjectEd', 'verbose_name_plural': 'Факультеты ProjectEd'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['name'], 'verbose_name': 'Роль ProjectEd', 'verbose_name_plural': 'Роли ProjectEd'},
        ),
    ]
