# Generated by Django 5.2.6 on 2025-09-22 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_ed', '0007_rename_projecteddepartment_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecteduserprofile',
            name='faculty_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='project_ed.faculty', verbose_name='Факультет (справочник)'),
        ),
        migrations.AlterField(
            model_name='projecteduserprofile',
            name='role_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='project_ed.role', verbose_name='Роль (справочник)'),
        ),
    ]
