# Generated by Django 5.2.6 on 2025-09-22 11:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_ed', '0008_alter_projecteduserprofile_faculty_ref_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectEdUserProfile',
            new_name='UserProfile',
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Профиль пользователя проекта', 'verbose_name_plural': 'Профили пользователей проекта'},
        ),
    ]
