# Generated by Django 5.2.6 on 2025-09-23 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_ed', '0014_remove_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='project_ed.faculty', verbose_name='Факультет'),
        ),
    ]
