# Generated by Django 5.2.6 on 2025-09-23 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_ed', '0015_department_faculty'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
