# Generated by Django 5.2.6 on 2025-09-25 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_ed', '0016_delete_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='targetindicator',
            name='current_value',
        ),
        migrations.RemoveField(
            model_name='targetindicator',
            name='description',
        ),
        migrations.RemoveField(
            model_name='targetindicator',
            name='project',
        ),
        migrations.RemoveField(
            model_name='targetindicator',
            name='target_value',
        ),
    ]
