# Generated by Django

from django.db import migrations


def add_categories_and_subcategories(apps, schema_editor):
    """Добавляет категории и подкатегории показателей проекта."""
    Category = apps.get_model('project_ed', 'Category')
    Subcategory = apps.get_model('project_ed', 'Subcategory')
    
    # Создаем категории
    category_a = Category.objects.create(
        name='Целевые показатели группы «Категория А»',
        description='Категория А',
        order=1,
        is_active=True
    )
    
    category_b = Category.objects.create(
        name='Целевые показатели группы «Категория Б»',
        description='Категория Б',
        order=2,
        is_active=True
    )
    
    # Создаем подкатегории для Категории А
    subcategory_a1 = Subcategory.objects.create(
        category=category_a,
        name='Интегральный показатель «Цифровая зрелость университета»',
        description='Интегральный показатель «Цифровая зрелость университета»',
        order=1,
        is_active=True
    )
    
    # Создаем подкатегории для Категории Б
    subcategories_b = [
        ('Стратегический проект №1 «Уникальные фундаментальные и прикладные исследования для укрепления технологического суверенитета страны»', 1),
        ('Стратегический проект №2 «Экосистема поддержки цифровых и технологических стартапов»', 2),
        ('Стратегический проект №3 «Доступное обучение информационным специальностям, отраслевой экономике и управлению»', 3),
        ('Стратегический проект №4 «Развитие молодежного креативного сектора»', 4),
        ('Стратегический проект №5 «Доступная инфраструктура для занятия спортом»', 5),
        ('ОП. Образовательная политика', 6),
        ('НП. Политика в области научно-исследовательской деятельности и инноваций', 7),
        ('МП. Молодежная политика', 8),
        ('КП. Политика по развитию человеческого капитала', 9),
        ('ИП. Политика по развитию инфраструктуры', 10),
        ('ЦТ. Политика в области цифровой трансформации', 11),
        ('УП. Система управления Университетом', 12),
        ('СП. Социальная миссия', 13),
        ('МД. Международная деятельность', 14),
    ]
    
    for name, order in subcategories_b:
        Subcategory.objects.create(
            category=category_b,
            name=name,
            description=name,
            order=order,
            is_active=True
        )


def remove_categories_and_subcategories(apps, schema_editor):
    """Удаляет добавленные категории и подкатегории."""
    Category = apps.get_model('project_ed', 'Category')
    Subcategory = apps.get_model('project_ed', 'Subcategory')
    
    # Удаляем подкатегории
    Subcategory.objects.filter(
        category__name__in=['Категория А', 'Категория Б']
    ).delete()
    
    # Удаляем категории
    Category.objects.filter(
        name__in=['Категория А', 'Категория Б']
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('project_ed', '0019_populate_departments'),
    ]

    operations = [
        migrations.RunPython(
            add_categories_and_subcategories,
            remove_categories_and_subcategories
        ),
    ]
