# Generated by Django 5.2.6 on 2025-09-29 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_ed', '0020_add_categories_and_subcategories_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventblock',
            name='category',
        ),
    ]
