# Generated by Django 5.2.6 on 2025-10-01 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_ed', '0021_remove_eventblock_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='basic_provisions',
        ),
        migrations.RemoveField(
            model_name='project',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='project',
            name='calendar_plan',
        ),
        migrations.RemoveField(
            model_name='project',
            name='curator_id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='manager_name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='target_indicators',
        ),
        migrations.AddField(
            model_name='project',
            name='curator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_ed_curated_projects', to=settings.AUTH_USER_MODEL, verbose_name='Куратор проекта'),
        ),
        migrations.AddField(
            model_name='project',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_ed_customer_projects', to=settings.AUTH_USER_MODEL, verbose_name='Заказчик проекта'),
        ),
        migrations.AddField(
            model_name='project',
            name='event_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='project_ed.eventblock', verbose_name='Блок мероприятий'),
        ),
        migrations.AddField(
            model_name='project',
            name='goal',
            field=models.TextField(blank=True, default='', verbose_name='Цель проекта'),
        ),
        migrations.AddField(
            model_name='project',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_ed_managed_projects', to=settings.AUTH_USER_MODEL, verbose_name='Руководитель проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='additional_info',
            field=models.TextField(blank=True, default='', verbose_name='Дополнительная информация'),
        ),
        migrations.AlterField(
            model_name='project',
            name='budget_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Бюджет (с учетом взносов)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='project_ed.event', verbose_name='Мероприятие'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На согласовании'), ('rejected', 'Отклонён'), ('active', 'Активен'), ('done', 'Завершён')], default='draft', max_length=32, verbose_name='Статус'),
        ),
    ]
