# Generated by Django 5.2.6 on 2025-09-07 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_analysis', '0002_alter_videoanalysis_audio_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoanalysis',
            name='subtitle_background_color',
            field=models.CharField(default='#000000', max_length=7, verbose_name='Цвет фона субтитров'),
        ),
        migrations.AddField(
            model_name='videoanalysis',
            name='subtitle_background_transparent',
            field=models.BooleanField(default=False, verbose_name='Прозрачный фон субтитров'),
        ),
        migrations.AddField(
            model_name='videoanalysis',
            name='subtitle_font_color',
            field=models.CharField(default='#FFFFFF', max_length=7, verbose_name='Цвет шрифта субтитров'),
        ),
        migrations.AddField(
            model_name='videoanalysis',
            name='subtitle_font_size',
            field=models.IntegerField(default=24, verbose_name='Размер шрифта субтитров'),
        ),
        migrations.AddField(
            model_name='videoanalysis',
            name='subtitle_lines_count',
            field=models.IntegerField(default=1, verbose_name='Количество строк субтитров одновременно'),
        ),
    ]
