# Generated by Django 5.2.6 on 2025-09-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_analysis', '0003_videoanalysis_subtitle_background_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoanalysis',
            name='tts_audio_file',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Путь к файлу озвучки'),
        ),
        migrations.AddField(
            model_name='videoanalysis',
            name='tts_enabled',
            field=models.BooleanField(default=False, verbose_name='Включить озвучку'),
        ),
        migrations.AddField(
            model_name='videoanalysis',
            name='tts_language',
            field=models.CharField(default='fr', help_text='ru - русский, fr - французский', max_length=10, verbose_name='Язык озвучки'),
        ),
        migrations.AddField(
            model_name='videoanalysis',
            name='tts_voice_model',
            field=models.CharField(default='silero_tts', max_length=50, verbose_name='Модель голоса'),
        ),
        migrations.AddField(
            model_name='videoanalysis',
            name='tts_volume',
            field=models.FloatField(default=0.7, verbose_name='Громкость озвучки (0.0-1.0)'),
        ),
    ]
