# Generated by Django 5.2.6 on 2025-09-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_analysis', '0004_videoanalysis_tts_audio_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoanalysis',
            name='subtitle_alignment',
            field=models.CharField(choices=[('bottom', 'Снизу'), ('top', 'Сверху'), ('center', 'По центру'), ('custom', 'Пользовательское')], default='bottom', max_length=10, verbose_name='Выравнивание субтитров'),
        ),
        migrations.AddField(
            model_name='videoanalysis',
            name='subtitle_margin_horizontal',
            field=models.IntegerField(default=0, verbose_name='Отступ по горизонтали (в пикселях)'),
        ),
        migrations.AddField(
            model_name='videoanalysis',
            name='subtitle_margin_vertical',
            field=models.IntegerField(default=20, verbose_name='Отступ по вертикали (в пикселях)'),
        ),
    ]
