# Generated by Django 5.2.6 on 2025-09-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_analysis', '0005_videoanalysis_subtitle_alignment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoanalysis',
            name='subtitle_alignment',
            field=models.CharField(choices=[('1', 'Слева снизу'), ('2', 'По центру снизу'), ('3', 'Справа снизу'), ('4', 'Сверху слева'), ('5', 'По центру слева'), ('6', 'Сверху по центру'), ('7', 'Сверху справа'), ('8', 'По центру'), ('9', 'Справа по центру')], default='2', max_length=1, verbose_name='Позиция субтитров'),
        ),
    ]
