# Generated by Django 5.2.5 on 2025-09-04 09:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpulsAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('analysis_type', models.CharField(choices=[('standard', 'Стандартный анализ'), ('advanced', 'Расширенный анализ'), ('custom', 'Пользовательский анализ')], default='standard', max_length=20, verbose_name='Тип анализа')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('processing', 'Обрабатывается'), ('completed', 'Завершен'), ('failed', 'Ошибка'), ('cancelled', 'Отменен')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало обработки')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершение обработки')),
                ('analysis_results', models.JSONField(blank=True, null=True, verbose_name='Результаты анализа')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('task_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID задачи Celery')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Анализ импульса',
                'verbose_name_plural': 'Анализы импульса',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImpulsForceRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sheet_title', models.CharField(blank=True, default='', max_length=255, verbose_name='Лист')),
                ('protocol_number', models.CharField(max_length=64, verbose_name='Номер протокола')),
                ('pct_static', models.FloatField(blank=True, null=True, verbose_name='Pст, %')),
                ('v', models.FloatField(blank=True, null=True, verbose_name='v')),
                ('p', models.FloatField(blank=True, null=True, verbose_name='p')),
                ('f', models.FloatField(blank=True, null=True, verbose_name='f')),
                ('energy_j', models.FloatField(blank=True, null=True, verbose_name='Энергия удара, Дж')),
                ('velocity_ms', models.FloatField(blank=True, null=True, verbose_name='Скорость удара, м/с')),
                ('force_n', models.FloatField(blank=True, null=True, verbose_name='Сила удара (P), Н')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Запись расчета силы',
                'verbose_name_plural': 'Записи расчета силы',
                'indexes': [models.Index(fields=['protocol_number'], name='impuls_anal_protoco_d1f08f_idx')],
            },
        ),
        migrations.CreateModel(
            name='ImpulsPlanRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('protocol_number', models.CharField(max_length=64, verbose_name='Номер протокола')),
                ('p_static', models.FloatField(blank=True, null=True, verbose_name='Pст, %')),
                ('p_static_value', models.FloatField(blank=True, null=True, verbose_name='Pст значение')),
                ('l1_l2_ratio', models.IntegerField(blank=True, null=True, verbose_name='L1/L2')),
                ('l1_m', models.FloatField(blank=True, null=True, verbose_name='L1 (м)')),
                ('d1_m', models.FloatField(blank=True, null=True, verbose_name='d1 (м)')),
                ('m1_kg', models.FloatField(blank=True, null=True, verbose_name='m1 (кг)')),
                ('l2_m', models.FloatField(blank=True, null=True, verbose_name='L2 (м)')),
                ('d2_m', models.FloatField(blank=True, null=True, verbose_name='d2 (м)')),
                ('t_s', models.FloatField(blank=True, null=True, verbose_name='Т (с)')),
                ('a_j', models.FloatField(blank=True, null=True, verbose_name='А, (Дж)')),
                ('v_ms', models.FloatField(blank=True, null=True, verbose_name='V, (м/с)')),
                ('c12_kg_s', models.FloatField(blank=True, null=True, verbose_name='С1,2 (кг/с)')),
                ('p_n', models.FloatField(blank=True, null=True, verbose_name='Р, (Н)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Запись плана эксперимента',
                'verbose_name_plural': 'Записи плана эксперимента',
                'indexes': [models.Index(fields=['protocol_number'], name='impuls_anal_protoco_0b2336_idx')],
            },
        ),
        migrations.CreateModel(
            name='ImpulsProtocol',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('protocol_file', models.FileField(upload_to='impuls_analysis/protocols/', verbose_name='Файл протокола')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Сгенерирован')),
                ('file_size', models.BigIntegerField(verbose_name='Размер файла (байт)')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocols', to='impuls_analysis.impulsanalysis', verbose_name='Анализ')),
            ],
            options={
                'verbose_name': 'Протокол анализа импульса',
                'verbose_name_plural': 'Протоколы анализа импульса',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='ImpulsFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_type', models.CharField(choices=[('force_calculation', 'Расчет силы'), ('experiment_plan', 'План эксперимента')], max_length=20, verbose_name='Тип файла')),
                ('file', models.FileField(upload_to='impuls_analysis/files/', verbose_name='Файл')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Оригинальное имя файла')),
                ('file_size', models.BigIntegerField(verbose_name='Размер файла (байт)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружен')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='impuls_analysis.impulsanalysis', verbose_name='Анализ')),
            ],
            options={
                'verbose_name': 'Файл анализа импульса',
                'verbose_name_plural': 'Файлы анализа импульса',
                'unique_together': {('analysis', 'file_type')},
            },
        ),
    ]
