# Generated by Django 5.2.5 on 2025-09-03 08:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpulsAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('analysis_type', models.CharField(choices=[('standard', 'Стандартный анализ'), ('advanced', 'Расширенный анализ'), ('custom', 'Пользовательский анализ')], default='standard', max_length=20, verbose_name='Тип анализа')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('processing', 'Обрабатывается'), ('completed', 'Завершен'), ('failed', 'Ошибка'), ('cancelled', 'Отменен')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало обработки')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершение обработки')),
                ('analysis_results', models.JSONField(blank=True, null=True, verbose_name='Результаты анализа')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('task_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID задачи Celery')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Анализ импульса',
                'verbose_name_plural': 'Анализы импульса',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImpulsProtocol',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('protocol_file', models.FileField(upload_to='impuls_analysis/protocols/', verbose_name='Файл протокола')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Сгенерирован')),
                ('file_size', models.BigIntegerField(verbose_name='Размер файла (байт)')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocols', to='impuls_analysis.impulsanalysis', verbose_name='Анализ')),
            ],
            options={
                'verbose_name': 'Протокол анализа импульса',
                'verbose_name_plural': 'Протоколы анализа импульса',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='ImpulsFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_type', models.CharField(choices=[('force_calculation', 'Расчет силы'), ('experiment_plan', 'План эксперимента')], max_length=20, verbose_name='Тип файла')),
                ('file', models.FileField(upload_to='impuls_analysis/files/', verbose_name='Файл')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Оригинальное имя файла')),
                ('file_size', models.BigIntegerField(verbose_name='Размер файла (байт)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружен')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='impuls_analysis.impulsanalysis', verbose_name='Анализ')),
            ],
            options={
                'verbose_name': 'Файл анализа импульса',
                'verbose_name_plural': 'Файлы анализа импульса',
                'unique_together': {('analysis', 'file_type')},
            },
        ),
    ]
