# Generated by Django 5.2.6 on 2025-09-04 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('impuls_analysis', '0002_remove_impulsanalysis_analysis_results_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impulsanalysis',
            name='detailed_image',
        ),
        migrations.RemoveField(
            model_name='impulsanalysis',
            name='plain_image',
        ),
    ]
