# Generated by Django 5.2.6 on 2025-09-07 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('impuls_analysis', '0003_remove_impulsanalysis_detailed_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impulsanalysis',
            name='analysis_type',
        ),
    ]
