# Generated by Django 5.2.6 on 2025-09-24 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impuls_analysis', '0004_remove_impulsanalysis_analysis_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='impulsanalysis',
            name='number',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='Номер анализа'),
        ),
    ]
