# Generated by Django 5.2.6 on 2025-09-23 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project_ed', '0016_delete_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=True, verbose_name='Публичный профиль')),
                ('show_email', models.BooleanField(default=False, verbose_name='Показывать email')),
                ('department_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='project_ed.department', verbose_name='Кафедра (справочник)')),
                ('faculty_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='project_ed.faculty', verbose_name='Факультет (справочник)')),
                ('position_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='project_ed.position', verbose_name='Должность (справочник)')),
                ('role_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='project_ed.role', verbose_name='Роль (справочник)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_ed_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
    ]
