# Generated by Django 5.2.6 on 2025-10-09 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project_ed', '0022_remove_project_basic_provisions_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('info', 'Информация'), ('warning', 'Предупреждение'), ('success', 'Успех'), ('error', 'Ошибка')], default='info', max_length=32, verbose_name='Тип')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('message', models.TextField(blank=True, default='', verbose_name='Сообщение')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Данные')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата прочтения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_ed_notifications_as_actor', to=settings.AUTH_USER_MODEL, verbose_name='Инициатор')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='project_ed.project', verbose_name='Проект')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_ed_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
            ],
            options={
                'verbose_name': 'Уведомление проекта',
                'verbose_name_plural': 'Уведомления проекта',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'created_at'], name='project_ed__project_29b9d4_idx'), models.Index(fields=['recipient', 'is_read', 'created_at'], name='project_ed__recipie_46ad8d_idx'), models.Index(fields=['type'], name='project_ed__type_b15a1f_idx')],
            },
        ),
    ]
