# Generated by Django 5.2.6 on 2025-10-09 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_ed_notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectNotificationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата прочтения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Доставка уведомления',
                'verbose_name_plural': 'Доставки уведомлений',
            },
        ),
        migrations.RemoveIndex(
            model_name='projectnotification',
            name='project_ed__recipie_46ad8d_idx',
        ),
        migrations.RemoveField(
            model_name='projectnotification',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='projectnotification',
            name='read_at',
        ),
        migrations.RemoveField(
            model_name='projectnotification',
            name='recipient',
        ),
        migrations.AddField(
            model_name='projectnotificationdelivery',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='project_ed_notifications.projectnotification', verbose_name='Уведомление'),
        ),
        migrations.AddField(
            model_name='projectnotificationdelivery',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_ed_notification_deliveries', to=settings.AUTH_USER_MODEL, verbose_name='Получатель'),
        ),
        migrations.AddIndex(
            model_name='projectnotificationdelivery',
            index=models.Index(fields=['recipient', 'is_read', 'created_at'], name='project_ed__recipie_b7d582_idx'),
        ),
        migrations.AddIndex(
            model_name='projectnotificationdelivery',
            index=models.Index(fields=['notification'], name='project_ed__notific_0e704a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectnotificationdelivery',
            unique_together={('notification', 'recipient')},
        ),
    ]
