# Generated by Django 5.2.6 on 2025-09-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_analytics_data_formalization_submodule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competency',
            name='blooms_level',
            field=models.CharField(choices=[('KNOW', 'Знание'), ('UNDERSTAND', 'Понимание'), ('APPLY', 'Применение'), ('ANALYZE', 'Анализ'), ('EVALUATE', 'Оценка'), ('CREATE', 'Создание')], default='KNOW', max_length=10, verbose_name='Уровень таксономии Блума'),
        ),
    ]
